# Generated by Django 4.2.2 on 2023-07-19 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0030_alter_expensee_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_tablee',
            name='vendor_display_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
