# Generated by Django 4.2.2 on 2023-07-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0031_alter_vendor_tablee_vendor_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_tablee',
            name='vendor_email',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
