# Generated by Django 4.2.2 on 2023-07-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0037_alter_vendor_tablee_baddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_tablee',
            name='baddress',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='battention',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='bcity',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='bcountry',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='bfax',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='bphone',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='bstate',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='bzip',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='company_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='currency',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='department',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='designation',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='gst_treatment',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='opening_bal',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='payment_terms',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='saddress',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='salutation',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='sattention',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='scity',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='scountry',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='sfax',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='skype_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='source_supply',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='sphone',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='sstate',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='szip',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='vendor_display_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='vendor_email',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='vendor_mphone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='vendor_wphone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='website',
            field=models.CharField(default='', max_length=250),
        ),
    ]
