# Generated by Django 4.2.2 on 2023-07-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0038_alter_vendor_tablee_baddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_tablee',
            name='company_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='currency',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='designation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='gst_treatment',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='opening_bal',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='payment_terms',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='salutation',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='skype_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='source_supply',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='vendor_display_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='vendor_email',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='vendor_mphone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='vendor_wphone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='website',
            field=models.CharField(max_length=250),
        ),
    ]
