# Generated by Django 4.2.2 on 2023-08-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0039_alter_vendor_tablee_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_tablee',
            name='currency',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='department',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='designation',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='gst_number',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='gst_treatment',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='opening_bal',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='pan_number',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='payment_terms',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='skype_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='source_supply',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='vendor_display_name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='vendor_email',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='vendor_mphone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='vendor_wphone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='website',
            field=models.CharField(default='', max_length=250),
        ),
    ]
