# Generated by Django 4.2.2 on 2023-08-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0041_alter_vendor_tablee_baddress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remarks_tablee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='remarks_tablee',
            name='vendor',
        ),
        migrations.AlterField(
            model_name='addcustomere',
            name='OpeningBalance',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='contact_person_tableE',
        ),
        migrations.DeleteModel(
            name='remarks_tableE',
        ),
    ]
