# Generated by Django 4.2.2 on 2023-08-04 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zohoapp', '0042_remove_remarks_tablee_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment_termsE',
        ),
        migrations.AlterField(
            model_name='vendor_tablee',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
