# Generated by Django 4.2.2 on 2023-08-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0044_alter_vendor_tablee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensee',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
