# Generated by Django 4.2.2 on 2023-08-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0045_alter_expensee_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensee',
            name='vendor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
