# Generated by Django 4.2.2 on 2023-08-07 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0047_alter_expensee_customer_name_alter_expensee_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensee',
            name='customer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zohoapp.addcustomere'),
        ),
        migrations.AlterField(
            model_name='expensee',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zohoapp.vendor_tablee'),
        ),
    ]
