# Generated by Django 4.2.2 on 2023-08-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0051_remove_expensee_expense_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensee',
            name='expense_account',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
