# Generated by Django 4.2.2 on 2023-08-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0052_expensee_expense_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensee',
            name='expense_account',
            field=models.CharField(default='', max_length=100),
        ),
    ]
