# Generated by Django 4.2.2 on 2023-08-17 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0060_expensee_gstin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensee',
            name='customer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.customer'),
        ),
        migrations.AlterField(
            model_name='expensee',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.vendor_table'),
        ),
    ]
