# Generated by Django 4.2.2 on 2023-08-23 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zohoapp', '0061_alter_expensee_customer_name_alter_expensee_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bankcreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=220, null=True)),
                ('branch', models.CharField(blank=True, default='', max_length=220, null=True)),
                ('ac_no', models.CharField(blank=True, default='', max_length=220, null=True)),
                ('ifsc', models.CharField(blank=True, default='', max_length=220, null=True)),
                ('opn_bal', models.IntegerField(blank=True, null=True)),
                ('bal_type', models.CharField(blank=True, default='', max_length=220, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
