# Generated by Django 4.2.2 on 2023-08-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0063_bank_to_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_to_cash',
            name='description',
            field=models.CharField(blank=True, default='', max_length=220, null=True),
        ),
    ]
