# Generated by Django 4.2.2 on 2023-08-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0065_transactions_delete_bank_to_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='type',
            field=models.CharField(blank=True, default='', max_length=220, null=True),
        ),
    ]
