# Generated by Django 4.2.2 on 2023-08-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0066_transactions_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcreation',
            name='opn_bal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
