# Generated by Django 4.2.2 on 2023-08-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0068_transactions_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='adjacname',
            field=models.CharField(blank=True, default='', max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='adjtype',
            field=models.CharField(blank=True, default='', max_length=220, null=True),
        ),
    ]
