# Generated by Django 4.2.2 on 2023-08-26 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0071_alter_transactions_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='balance',
        ),
    ]
