# Generated by Django 4.2.2 on 2023-08-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0072_remove_transactions_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='balance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
