# Generated by Django 4.2.2 on 2023-08-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0074_remove_transactions_balance_bankcreation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankcreation',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='doc/bank'),
        ),
    ]
