# Generated by Django 4.2.2 on 2023-08-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0075_bankcreation_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcreation',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='bank/'),
        ),
    ]
