# Generated by Django 4.2.2 on 2023-09-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0076_alter_bankcreation_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankcreation',
            name='status',
            field=models.TextField(default='active'),
        ),
    ]
